<?php
return [
    [
        'business_name' => 'Byness s.r.l',
        'status' => 'Business',
        'vat_number' => '12345678901',
        'tax_id_code' => '1234567890987654',
        'address' => 'Via del Melo 12',
        'activity_start_date' => '14/10/1965',
        'rating' => 'A',
        // 'chamber_of_commerce' => '',
        'notes' => 'Azienda che produce carta igienica e scottex',
        'email' => 'byness@byness.it',
        'phone_number' => '0572910705',
        'username' => 'Byness65',
        'password' => 'password'
    ],
    [
        'business_name' => 'Pieraccini s.r.l',
        'status' => 'Business',
        'vat_number' => '12345678902',
        'tax_id_code' => '1234567890987653',
        'address' => 'Corso Roma 126',
        'activity_start_date' => '18/04/1992',
        'rating' => 'B',
        // 'chamber_of_commerce' => '',
        'notes' => 'Negozio di informatiza e tecnologia',
        'email' => 'pieraccini@pieraccini.it',
        'phone_number' => '0572910704',
        'username' => 'Pieraccini92',
        'password' => 'password'
    ],
    [
        'business_name' => 'MHS s.a.s',
        'status' => 'Business',
        'vat_number' => '12345678903',
        'tax_id_code' => '1234567890987652',
        'address' => 'Corso Roma 35',
        'activity_start_date' => '15/05/1985',
        'rating' => 'C',
        // 'chamber_of_commerce' => '',
        'notes' => 'Parrucchiere uomo/donna',
        'email' => 'mhs@mhs.it',
        'phone_number' => '0572910703',
        'username' => 'Mhs85',
        'password' => 'password'
    ],
    [
        'business_name' => 'Da Lorenzo s.a.s',
        'status' => 'Business',
        'vat_number' => '12345678904',
        'tax_id_code' => '1234567890985849',
        'address' => 'Via Bonini 65',
        'activity_start_date' => '12/09/1967',
        'rating' => 'A',
        // 'chamber_of_commerce' => '',
        'notes' => 'Ristorante di pesce',
        'email' => 'lorenzo@lorenzo.it',
        'phone_number' => '0572910708',
        'username' => 'Lorenzo67',
        'password' => 'password'
    ],
    [
        'business_name' => 'Da Gomma',
        'status' => 'Business',
        'vat_number' => '12345678905',
        'tax_id_code' => '1234567890983585',
        'address' => 'Via delle canterelle 18',
        'activity_start_date' => '28/05/1999',
        'rating' => 'B',
        // 'chamber_of_commerce' => '',
        'notes' => 'Gelateria',
        'email' => 'gomma@gomma.it',
        'phone_number' => '0572910703',
        'username' => 'Gomma99',
        'password' => 'password'
    ],
    [
        'business_name' => 'Masisi s.r.l',
        'status' => 'Business',
        'vat_number' => '12345678906',
        'tax_id_code' => '1234567890987480',
        'address' => 'Via di riaffrico 29',
        'activity_start_date' => '07/10/1993',
        'rating' => 'A',
        // 'chamber_of_commerce' => '',
        'notes' => 'Azienda agricola',
        'email' => 'masini@masini.it',
        'phone_number' => '0572910703',
        'username' => 'Masini93',
        'password' => 'password'
    ],
];
